### ISSUE TITLE
Montando pool error

### ISSUE THREAD

**Issue by equisde** [cryptoluka/CryptoLuKa#15]
hola al querer montar una pool me da error al hacer npm update con la pool que ustedes tienen en su repo
nodejs v0.10.25

al momento de hacer npm update me da el siguiente error

```
/root/luka-pool/node_modules/bignum/node_modules/prebuild-install/node_modules/which-pm-runs/index.js:11
  const pmSpec = userAgent.split(' ')[0]
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/luka-pool/node_modules/bignum/node_modules/prebuild-install/bin.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
make: Entering directory '/root/luka-pool/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
cli-color@1.2.0 node_modules/cli-color
├── ansi-regex@2.1.1
├── d@1.0.0
├── timers-ext@0.1.5 (next-tick@1.0.0)
├── es6-iterator@2.0.3 (es6-symbol@3.1.1)
├── memoizee@0.4.14 (is-promise@2.1.0, lru-queue@0.1.0, next-tick@1.0.0, event-emitter@0.3.5, es6-weak-map@2.0.2)
└── es5-ext@0.10.46 (next-tick@1.0.0, es6-symbol@3.1.1)
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  COPY Release/bignum.node
make: Leaving directory '/root/luka-pool/node_modules/bignum/build'

> bignum@0.13.0 install /root/luka-pool/node_modules/base58-native/node_modules/bignum
> prebuild-install || node-gyp rebuild

bignum@0.13.0 node_modules/bignum
├── bindings@1.3.0
├── safe-buffer@5.1.2
├── nan@2.10.0
└── prebuild-install@4.0.0 (which-pm-runs@1.0.0, os-homedir@1.0.2, expand-template@1.1.1, tunnel-agent@0.6.0, noop-logger@0.1.1, detect-libc@1.0.3, github-from-package@0.0.0, minimist@1.2.0, rc@1.2.8, node-abi@2.4.3, simple-get@2.8.1, pump@2.0.1, npmlog@4.1.2, mkdirp@0.5.1, tar-fs@1.16.3)

/root/luka-pool/node_modules/base58-native/node_modules/bignum/node_modules/prebuild-install/node_modules/which-pm-runs/index.js:11
  const pmSpec = userAgent.split(' ')[0]
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/luka-pool/node_modules/base58-native/node_modules/bignum/node_modules/prebuild-install/bin.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
make: Entering directory '/root/luka-pool/node_modules/base58-native/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  COPY Release/bignum.node
make: Leaving directory '/root/luka-pool/node_modules/base58-native/node_modules/bignum/build'

> cryptonote-util@0.0.1 install /root/luka-pool/node_modules/cryptonote-util
> node-gyp rebuild

base58-native@0.1.4 node_modules/base58-native
└── bignum@0.13.0 (bindings@1.3.0, safe-buffer@5.1.2, nan@2.10.0, prebuild-install@4.0.0)
make: Entering directory '/root/luka-pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
  CC(target) Release/obj.target/cryptonote/src/crypto/crypto-ops.o
  CC(target) Release/obj.target/cryptonote/src/crypto/crypto-ops-data.o
  CC(target) Release/obj.target/cryptonote/src/crypto/hash.o
  CC(target) Release/obj.target/cryptonote/src/crypto/keccak.o
  CXX(target) Release/obj.target/cryptonote/src/common/base58.o
^Ccryptonote.target.mk:103: recipe for target 'Release/obj.target/cryptonote/src/common/base58.o' failed
make: *** [Release/obj.target/cryptonote/src/common/base58.o] Interrupt
root@ubuntu:~/luka-pool# 


```

presione control + c solo para obtener el error 
al hacer npm update deje que todo terminara ignorando esos errores modifique el archivo config.json
ejecute el comando node init.js  
no da errores pero al ingresar al sitio este se queda en blanco verifique que el puerto del api fuera el mismo pero el sitio sigue arrojando la web en blanco 

![image](https://user-images.githubusercontent.com/34652149/44281415-15a30280-a22e-11e8-9fc3-5a5be4722a22.png)

alguna orientacion?

**Comment by Arielony** [comment]
npm install bignum
